name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    # environment: 
    #   name: production
    # permissions:
    #   contents: write
    steps:
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
            filename: github-metrics/isocalendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes